### ISSUE TITLE
helm-flx-fuzzy-highlighter wrong-type-argument stringp nil

### ISSUE THREAD

**Issue by simendsjo** [bbatsov/helm-projectile#94] opened 2018-03-22 07:56 UTC
## Expected behavior
helm-projectile opens project

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Error is raised

## Steps to reproduce (recipe)
`helm-projectile-switch-project` then select project

## Backtraces if any (`M-x toggle-debug-on-error`)

![capture](https://user-images.githubusercontent.com/351519/37755895-90dd0ad2-2da7-11e8-9076-27dbcc282078.PNG)

## Environment & version information

- `helm-projectile` version: helm-projectile-20180321.324
- `helm` version (in `helm-pkg.el`): 
```elisp
(define-package "helm" "20180321.116" "Helm is an Emacs incremental and narrowing framework"
  '((emacs "24.4")
    (async "1.9.2")
    (popup "0.5.3")
    (helm-core "2.9.0"))
  :url "https://emacs-helm.github.io/helm/")
```
- `projectile` version (`M-x projectile-version`): Projectile 20180317.2220
- Emacs version (`M-x emacs-version`): GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-12
- Spacemacs v.0.300.0 (develop branch commit 0fa3658cd8e283825dcd0a54ce1579dec55eb568)
- OS: Windows 10 v1709 (OS Build 16299.309)

**Comment by simendsjo** [comment] 2018-03-22 07:56
This is duplicate of https://github.com/emacs-helm/helm/issues/2001 as it wasn't related to helm

**Comment by xiongtx** [comment] 2018-03-23 00:45
Looks like it's fixed in Helm.

**Comment by xiongtx** [comment] 2018-03-23 01:59
Hmm, I cannot reproduce w/ `helm-projectile-20180321.324` and `helm-20180321.116`.

Can you try w/ vanilla Emacs and see if this is a Spacemacs-exclusive issue?

**Comment by simendsjo** [comment] 2018-03-23 05:14
> Hmm, I cannot reproduce w/ helm-projectile-20180321.324 and helm-20180321.116.

I thought it was verified and fixed in #95  ?

> Can you try w/ vanilla Emacs and see if this is a Spacemacs-exclusive issue?

I don't really know emacs that well, so it would take me some time. I'm also off for two weeks, so it would have to be after that..

**Comment by simendsjo** [comment] 2018-03-23 05:17
I can verify that it works for me (on Windows) now. Thanks!

**Comment by xiongtx** [comment] 2018-03-23 06:42
No reason #95 should fix any 🐛... it's a new feature.

But 😃 to hear things are working again.

**Closed by xiongtx** 2018-03-23 06:42 UTC
Labels: cannot_reproduce
