### ISSUE TITLE
delete disorderly in minibuffer 

### ISSUE THREAD

**Issue by ambjlon** [bbatsov/helm-projectile#100] opened 2018-03-30 02:59 UTC
When delete in minibuffer, the display is in wild disorder as below:
![2018-03-30 10 49 55](https://user-images.githubusercontent.com/4489822/38122702-1c0cb726-3409-11e8-8425-8bd403f7ec30.gif)

**Comment by xiongtx** [comment] 2018-04-08 02:35
Which command is this?

That looks like `helm-find-files`, which is part of [Helm](https://github.com/emacs-helm/helm) itself, not `helm-projectile`. But I cannot reproduce w/ `helm-find-files`.

**Comment by Asalle** [comment] 2019-06-18 18:41
Cannot reproduce it as well, @ambjlon could you provide more details?

**Comment by xiongtx** [comment] 2019-06-18 18:58
Going to close this as it cannot be reproduced. Feel free to reopen w/ more info.

**Closed by xiongtx** 2019-06-18 18:58 UTC
Labels: cannot_reproduce
